# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="nmariz"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
  git
  pyenv
  extract
)

source $ZSH/oh-my-zsh.sh

# Customize $PATH
export PATH=$HOME/bin:$HOME/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/opt/local/bin:$PATH

# Java
JAVA_HOME=/usr/local/java/jdk
PATH=$PATH:$JAVA_HOME/bin
export JAVA_HOME

# Golang
export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin

# Rust
export PATH=$PATH:$HOME/.cargo/bin

# Rust source path
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

# Editor
export EDITOR=vim
export ALTERNATE_EDITOR="emacs -nw"

# Aliases
alias v='nvim'
alias e='emacsclient -c -n'
alias et='emacsclient -c -t'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias ll='ls -lha'
alias open='xdg-open'
alias grep='grep --color=always -n'
alias rg='rg --color=always -n'
alias rm_pyc='find . -name \*.pyc -delete'
alias restart_force_check='sudo touch /forcefsck && sudo reboot'
alias dud='du -hs * | sort -rh | head -10'
alias git_pull_folders='ls | xargs -I{} git -C {} pull'
manage() { python manage.py $* --settings=settings_debug; }

# Pyenv
if [ -x "$(command -v ~/.pyenv/bin/pyenv)" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# Disable auto title in Tmuxinator
export DISABLE_AUTO_TITLE=true

# LANG
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Neofetch
if [ -x "$(command -v screenfetch)" ]; then
    screenfetch
fi

# Command-line fuzzy finder
# https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Alacritty
fpath+=${ZDOTDIR:-~}/.zsh_functions
